services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: consistent_bets
    ports:
      - '5432:5432'
    expose:
      - '5432'